(part "CR0805-FX-1543ELF"
    (packageRef "RESC2012X60N")
    (interface
        (port "1" (symbPinId 1) (portName "1") (portType INOUT))
        (port "2" (symbPinId 2) (portName "2") (portType INOUT))
    )
    (partClass UNDEF)
    (useInSchema Y)
    (useInLayout Y)
    (inPartsList Y)
    (partType NORMAL)
    (placeRestriction FREE)
    (property "compKind" "131")
    (property "Mouser_Part_Number" "652-CR0805FX-1543ELF")
    (property "Mouser_Price/Stock" "https://www.mouser.co.uk/ProductDetail/Bourns/CR0805-FX-1543ELF?qs=Hqdsf0hGw%2FDRTThedSiXGA%3D%3D")
    (property "Manufacturer_Name" "Bourns")
    (property "Manufacturer_Part_Number" "CR0805-FX-1543ELF")
    (property "Description" "Thick Film Resistors - SMD 154K 1%")
    (property "Datasheet_Link" "https://www.bourns.com/pdfs/chpreztr.pdf")
    (property "symbolName1" "CR0805-FX-1543ELF")
)
