(part "TS5A3359DCUT"
    (packageRef "SOP50P310X90-8N")
    (interface
        (port "1" (symbPinId 1) (portName "NO0") (portType INOUT))
        (port "2" (symbPinId 2) (portName "NO1") (portType INOUT))
        (port "3" (symbPinId 3) (portName "NO2") (portType INOUT))
        (port "4" (symbPinId 4) (portName "GND") (portType INOUT))
        (port "5" (symbPinId 5) (portName "IN2") (portType INOUT))
        (port "6" (symbPinId 6) (portName "IN1") (portType INOUT))
        (port "7" (symbPinId 7) (portName "COM") (portType INOUT))
        (port "8" (symbPinId 8) (portName "VCC") (portType INOUT))
    )
    (partClass UNDEF)
    (useInSchema Y)
    (useInLayout Y)
    (inPartsList Y)
    (partType NORMAL)
    (placeRestriction FREE)
    (property "compKind" "162")
    (property "Mouser_Part_Number" "595-TS5A3359DCUT")
    (property "Mouser_Price/Stock" "https://www.mouser.co.uk/ProductDetail/Texas-Instruments/TS5A3359DCUT?qs=0O%2FZFlpUpJWZahDSKJBJfQ%3D%3D")
    (property "Manufacturer_Name" "Texas Instruments")
    (property "Manufacturer_Part_Number" "TS5A3359DCUT")
    (property "Description" "Texas Instruments TS5A3359DCUT, Analogue Switch Single SP3T, 3.3 V, 5 V, 8-Pin VSSOP")
    (property "Datasheet_Link" "http://www.ti.com/general/docs/lit/getliterature.tsp?genericPartNumber=TS5A3359&&fileType=pdf")
    (property "symbolName1" "TS5A3359DCUT")
)
