(part "ADG884BRMZ"
    (packageRef "SOP50P490X110-10N")
    (interface
        (port "1" (symbPinId 1) (portName "VDD") (portType INOUT))
        (port "2" (symbPinId 2) (portName "S1A") (portType INOUT))
        (port "3" (symbPinId 3) (portName "D1") (portType INOUT))
        (port "4" (symbPinId 4) (portName "IN1") (portType INOUT))
        (port "5" (symbPinId 5) (portName "S1B") (portType INOUT))
        (port "6" (symbPinId 6) (portName "GND") (portType INOUT))
        (port "7" (symbPinId 7) (portName "S2B") (portType INOUT))
        (port "8" (symbPinId 8) (portName "IN2") (portType INOUT))
        (port "9" (symbPinId 9) (portName "D2") (portType INOUT))
        (port "10" (symbPinId 10) (portName "S2A") (portType INOUT))
    )
    (partClass UNDEF)
    (useInSchema Y)
    (useInLayout Y)
    (inPartsList Y)
    (partType NORMAL)
    (placeRestriction FREE)
    (property "compKind" "101")
    (property "Mouser_Part_Number" "584-ADG884BRMZ")
    (property "Mouser_Price/Stock" "https://www.mouser.co.uk/ProductDetail/Analog-Devices/ADG884BRMZ?qs=BpaRKvA4VqHGAEKiRnJ1Qg%3D%3D")
    (property "Manufacturer_Name" "Analog Devices")
    (property "Manufacturer_Part_Number" "ADG884BRMZ")
    (property "Description" "ADG884BRMZ, Analogue SPDT Switch Dual SPDT, 3, 5V, 10-Pin, MSOP")
    (property "Datasheet_Link" "http://www.analog.com/static/imported-files/data_sheets/ADG884.pdf")
    (property "symbolName1" "ADG884BRMZ")
)
