(part "AD8510ARZ-REEL"
    (packageRef "SOIC127P600X175-8N")
    (interface
        (port "1" (symbPinId 1) (portName "NULL_1") (portType INOUT))
        (port "2" (symbPinId 2) (portName "-IN") (portType INOUT))
        (port "3" (symbPinId 3) (portName "+IN") (portType INOUT))
        (port "4" (symbPinId 4) (portName "V-") (portType INOUT))
        (port "5" (symbPinId 5) (portName "NULL_2") (portType INOUT))
        (port "6" (symbPinId 6) (portName "OUT") (portType INOUT))
        (port "7" (symbPinId 7) (portName "V+") (portType INOUT))
        (port "8" (symbPinId 8) (portName "NC") (portType INOUT))
    )
    (partClass UNDEF)
    (useInSchema Y)
    (useInLayout Y)
    (inPartsList Y)
    (partType NORMAL)
    (placeRestriction FREE)
    (property "compKind" "101")
    (property "Mouser_Part_Number" "584-AD8510ARZ-R")
    (property "Mouser_Price/Stock" "https://www.mouser.co.uk/ProductDetail/Analog-Devices/AD8510ARZ-REEL?qs=%2FtpEQrCGXCwXL7drMaFeVQ%3D%3D")
    (property "Manufacturer_Name" "Analog Devices")
    (property "Manufacturer_Part_Number" "AD8510ARZ-REEL")
    (property "Description" "Precision, Very Low Noise, Low Input Bias Current, Wide Bandwidth JFET Single Operational Amplifier")
    (property "Datasheet_Link" "https://www.analog.com/AD8510/datasheet")
    (property "symbolName1" "AD8510ARZ-REEL")
)
