(part "0805X7R106KT1AT"
    (packageRef "CAPC2013X113N")
    (interface
        (port "1" (symbPinId 1) (portName "1") (portType INOUT))
        (port "2" (symbPinId 2) (portName "2") (portType INOUT))
    )
    (partClass UNDEF)
    (useInSchema Y)
    (useInLayout Y)
    (inPartsList Y)
    (partType NORMAL)
    (placeRestriction FREE)
    (property "compKind" "32")
    (property "Mouser_Part_Number" "581-0805X7R106KT1AT")
    (property "Mouser_Price/Stock" "https://www.mouser.co.uk/ProductDetail/KYOCERA-AVX/0805X7R106KT1AT?qs=XAiT9M5g4x%252Bo4s7i6ql7Og%3D%3D")
    (property "Manufacturer_Name" "Kyocera AVX")
    (property "Manufacturer_Part_Number" "0805X7R106KT1AT")
    (property "Description" "Multilayer Ceramic Capacitors MLCC - SMD/SMT CAP-RESALE")
    (property "Datasheet_Link" "https://datasheets.kyocera-avx.com/Accu-P.pdf")
    (property "symbolName1" "0805X7R106KT1AT")
)
