(part "TMUX1119DBVR"
    (packageRef "SOT95P280X145-6N")
    (interface
        (port "1" (symbPinId 1) (portName "SEL") (portType INOUT))
        (port "2" (symbPinId 2) (portName "VDD") (portType INOUT))
        (port "3" (symbPinId 3) (portName "GND") (portType INOUT))
        (port "4" (symbPinId 4) (portName "S1") (portType INOUT))
        (port "5" (symbPinId 5) (portName "D") (portType INOUT))
        (port "6" (symbPinId 6) (portName "S2") (portType INOUT))
    )
    (partClass UNDEF)
    (useInSchema Y)
    (useInLayout Y)
    (inPartsList Y)
    (partType NORMAL)
    (placeRestriction FREE)
    (property "compKind" "101")
    (property "Mouser_Part_Number" "595-TMUX1119DBVR")
    (property "Mouser_Price/Stock" "https://www.mouser.co.uk/ProductDetail/Texas-Instruments/TMUX1119DBVR?qs=9r4v7xj2Lnn%2FqYCDWCSZ7w%3D%3D")
    (property "Manufacturer_Name" "Texas Instruments")
    (property "Manufacturer_Part_Number" "TMUX1119DBVR")
    (property "Description" "Analog Switch ICs 3-pA, 5-V, 2:1 (SPDT), 1-channel precision multiplexer")
    (property "Datasheet_Link" "https://www.ti.com/lit/gpn/TMUX1119")
    (property "symbolName1" "TMUX1119DBVR")
)
